version: '3.8'
services:
  web:
    build: .
    container_name: 'app'
    command: python manage.py runserver 0:80
    ports:
      - 8000:8000
    volumes:
      - .:/app
      - django_static_volume:/usr/src/app/static
      - django_media_volume:/usr/src/app/media
    networks:
      - myNetwork
    depends_on:
      - make-migrate
      - migrate

  migrate:
    build: .
    container_name: 'migrate_app'
    command: python manage.py migrate --noinput
    volumes:
      - .:/app
    depends_on:
      - make-migrate

  make-migrate:
    build: .
    container_name: 'makemigrations_app'
    command: python manage.py makemigrations --noinput
    volumes:
      - .:/app

  node:

    build: ./reactapp

    container_name: reactapp

    restart: always

    ports:
      - 3000:3000

    command: npm start

    depends_on:
      - django

    networks:
      - myNetwork
    volumes:
      - ./reactapp/public/:/usr/src/app/public/
      - ./reactapp/src/:/usr/src/app/src/
volumes:
  django_static_volume:
  django_media_volume:
  rabbitmq_data_volume: