# Generated by Django 4.2 on 2023-04-11 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('categoty', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.TextField(max_length=50)),
                ('second_name', models.TextField(blank=True, max_length=50, null=True)),
                ('last_name', models.TextField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('phone', models.TextField(max_length=20)),
                ('about', models.TextField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Executor',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.TextField(max_length=50)),
                ('second_name', models.TextField(blank=True, max_length=50, null=True)),
                ('last_name', models.TextField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('phone', models.TextField(max_length=20)),
                ('about', models.TextField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('min_price', models.IntegerField()),
                ('max_price', models.IntegerField()),
                ('about', models.TextField(max_length=250)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend.categories')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend.client')),
            ],
        ),
        migrations.CreateModel(
            name='Total_Trade',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('price', models.IntegerField()),
                ('about', models.TextField(max_length=250)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend.categories')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend.client')),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend.executor')),
            ],
        ),
        migrations.CreateModel(
            name='E_Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend.executor')),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend.trade')),
            ],
        ),
        migrations.CreateModel(
            name='E_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend.categories')),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend.executor')),
            ],
        ),
        migrations.CreateModel(
            name='Donate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend.executor')),
            ],
        ),
    ]
